services:
  nginx:
    image: nginx:alpine
    container_name: portainer_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - portainer_networks
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_networks
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: database_mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_username
      MYSQL_DATABASE: mysql_username
      MYSQL_USER: mysql_password
      MYSQL_PASSWORD: root_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - portainer_networks

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_ukip
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database_mariadb
    networks:
      - portainer_networks
    restart: unless-stopped

volumes:
  data:
  mariadb:

networks:
  portainer_networks:
